name: Rust (Stable)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install APT Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends libsqlite3-dev

    - name: Update Rust
      run: rustup update stable

    - name: Build
      run: cargo +stable build --verbose

    - name: Run tests
      run: cargo +stable test --verbose
