name: Rust

on: [push]

jobs:
  stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install APT Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends libsqlite3-dev

    - name: Update Rust
      run: rustup update stable

    - name: Build
      run: cargo +stable build --all --all-features --verbose

    - name: Run tests
      run: cargo +stable test --all --all-features --verbose

    - name: Run examples
      run: |
        cargo +stable run --all-features --example blobs --verbose
        cargo +stable run --all-features --example macro --verbose
        cargo +stable run --all-features --example readme --verbose
  nightly:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install APT Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends libsqlite3-dev

    - name: Update Rust
      run: rustup update nightly

    - name: Build
      run: cargo +nightly build --all --all-features --verbose

    - name: Run tests
      run: cargo +nightly test --all --all-features --verbose

    - name: Run examples
      run: |
        cargo +nightly run --all-features --example blobs --verbose
        cargo +nightly run --all-features --example macro --verbose
        cargo +nightly run --all-features --example readme --verbose
